<a href="https://colab.research.google.com/github/mdreduanulhoque/AI_ML_Expert_with_Phitron/blob/main/Machine_Learning/Module_13/ML_Assignment_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

## Exam Instructions:
1. প্রথমে নিচের cell এ নিজের **নাম** এবং কোর্সে registration করা **ইমেইল** দিবে
2. Question wise numbering করে Text cell রাখবে এবং এর নিচে Code cell থাকবে, চেষ্টা করবে একটি code cell এ একটি question উত্তর দেওয়ার
3. Google Colab এর মধ্যে কোডগুলো করবে
4. এবং সেই ফাইলটি **'Anyone with the link' & 'View' Access** দিয়ে ফাইলটির Shareable Link টি সাবমিট করবে

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [ ]:
# Fill in your information
name = "MD Reduanul Hoque"           # Write your full name here
email = "mdreduanulhoquesadik@gmail.com"          # Write your registered email here

print(f"Name  : {name}")
print(f"Email : {email}")

Name  : MD Reduanul Hoque
Email : mdreduanulhoquesadik@gmail.com

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [5]:
# Question 1
df = pd.read_csv("house_price_regression_dataset.csv")
df.head(10)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
5,3944,5,3,1990,2.475930,2,8,8.797970e+05
6,3671,1,2,2012,4.911960,0,1,8.144279e+05
7,3419,1,1,1972,2.805281,1,1,7.034131e+05
8,630,3,3,1997,1.014286,1,8,1.738750e+05
9,2185,4,2,1981,3.941604,2,5,5.041765e+05

In [4]:
df.sample(5)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
839,4725,4,2,1953,3.656225,2,2,993240.281363
325,2193,4,1,1996,4.731886,0,6,530004.342842
547,3279,4,2,1990,1.503779,2,6,695362.741532
450,4136,5,3,1995,3.187816,2,8,926531.810009
985,4094,4,1,2021,3.795748,1,10,933332.720126

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [11]:
#Question 2
print(df.isnull().sum() )  ## No missing values
X = df.drop(columns=["House_Price"])
y = df["House_Price"]

x_train, x_test, y_train, t_test = train_test_split(X, y, test_size=0.2, random_state=42)

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [ ]:
#Question 4

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [23]:
# Question 5
X = df.drop(columns=["House_Price"])
y = df["House_Price"]

num_feature = X.select_dtypes(include=["number"]).columns

num_transformer = Pipeline(
    steps = [
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

preprocessor = ColumnTransformer(
    transformers= [
        ("num", num_transformer, num_feature)
    ]
)

sgd_pipeline = Pipeline(
    steps= [
        ("preprocessor", preprocessor),
        ("model", SGDRegressor(random_state= 42))
    ]
)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

sgd_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality'],
      dtype='object'))])),
                ('model', SGDRegressor(random_state=42))])

In [25]:
sgd_pipeline.predict(x_test.iloc[:10])

array([ 868606.82473284,  490302.03011793,  945600.29677529,
       1033346.43292947,  776632.74930873,  732421.02526197,
        995053.43847321,  885145.15111888,  796673.52306974,
        931619.48791984])

In [28]:
y_predict = sgd_pipeline.predict(x_test)
rmse = round(np.sqrt(mean_squared_error(y_test, y_predict)),4)
r2 = round(r2_score(y_test, y_predict),4)
print(rmse)
print(r2)

10075.1341
0.9984

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [29]:
# Question 6
X = df.drop(columns=["House_Price"])
y = df["House_Price"]

num_feature = X.select_dtypes(include=["number"]).columns

num_transformer = Pipeline(
    steps = [
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

preprocessor = ColumnTransformer(
    transformers= [
        ("num", num_transformer, num_feature)
    ]
)

lr_pipeline = Pipeline(
    steps= [
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality'],
      dtype='object'))])),
                ('model', LinearRegression())])

In [30]:
lr_pipeline.predict(x_test.iloc[:10])

array([ 868687.10747904,  490337.89825447,  945667.12422538,
       1033402.87599249,  776698.77390588,  732444.09335309,
        995051.99156274,  885174.76924364,  796730.53817138,
        931741.09209273])

In [31]:
y_predict = lr_pipeline.predict(x_test)
rmse = round(np.sqrt(mean_squared_error(y_test, y_predict)),4)
r2 = round(r2_score(y_test, y_predict),4)
print(rmse)
print(r2)

10071.4844
0.9984

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [ ]:
# Question 7